local Constants = {}

Constants.State_taxrate = {
    {"AL", "Alabama", "4.00%"},
    {"AK", "Alaska", "0%, but individual municipalities can set their own taxation rates :/"},
    {"AZ", "Arizona", "5.60% (Transaction Privilege Tax)"},
    {"AR", "Arkansas", "6.50%"},
    {"CA", "Calafornia", "7.25%"},
    {"CO", "Colorado", "2.90%"},
    {"CT", "Connecticut", "6.35%"},
    {"DE", "Delaware", "None :)"},
    {"FL", "Florida", "6.00%"},
    {"GA", "Georgia", "4.00% (Can increase due to local tax rates)"},
    {"HI", "Hawaii", "4.00%"},
    {"ID", "Idaho", "6.00%"},
    {"IL", "Illinois", "6.25% (Can increase due to local municipalities)"},
    {"IN", "Indiana", "7.00%"},
    {"IA", "Iowa", "6.00%"},
    {"KS", "Kansas", "6.50%"},
    {"KY", "Kentucky", "6.00%"},
    {"LA", "Louisiana", "4.45% (Can increase to up to 11.45% due to local municipalities)"},
    {"ME", "Maine", "5.50%"},
    {"MD", "Maryland", "6.00%"},
    {"MA", "Massachusettes", "6.25%"},
    {"MI", "Meatchicken", "92.01% Don't go to Meatchicken >:("},
    {"MN", "Minnesota", "6.875%"},
    {"MS", "Mississipi", "7.00%"},
    {"MO", "Missouri", "4.225%"},
    {"MT", "Montana", "None :)"},
    {"NE", "Nebraska", "5.50%"},
    {"NV", "Nevada", "6.85%"},
    {"NH", "New Hampshire", "None : )"},
    {"NJ", "New Jersey", "6.625"},
    {"NM", "New Mexico", "5.125"},
    {"NY", "New York", "4.5% (can go up to 8% due to multiple circumstances..)"},
    {"NC", "North Carolina", "4.75%"},
    {"ND", "North Dakota", "5.00%"},
    {"OH", "Ohio", "7.25%", "tseT"},
    {"OK", "Oklahoma", "4.50%"},
    {"OR", "Oregon", "0%"},
    {"PA", "Pennsylvania", "6.00%"},
    {"RI", "Rhode Island", "7.00%"},
    {"SC", "South Carolina", "6.00%"},
    {"SD", "South Dakota", "4.50%"},
    {"TN", "Tennessee", "7.00%"},
    {"TX", "Texas", "6.25%"},
    {"UT", "Utah", "4.85%"},
    {"VT", "Vermont", "6.00%"},
    {"VA", "Virginia", "5.30%"},
    {"WA", "Washington", "6.50%"},
    {"WV", "West Virginia", "6.00%"},
    {"WI", "Wisconsin", "5.00%"},
    {"WY", "Wyoming", "4.00%"}

}

Constants.State_list = {
"All 50 US States:",
"AL AK AZ AR CA CO CT DE FL GA", 
"HI ID IL IN IA KS KY LA ME MD", 
"MA MI MN MS MO MT NE NV NH NJ", 
"NM NY NC ND OH OK OR PA RI SC",
"SD TN TX UT VT VA WA WV WI WY"}

return Constants
